services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: my-node-app
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
